// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfkusbwsvbdkqspxrvwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFma3VzYndzdmJka3FzcHhydnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTcxNTYsImV4cCI6MjA3NDEzMzE1Nn0.RTL28e7A8AknGTUOf5NdbifdfhTjtn_V6vG8Rg-fyIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});